on: [push, pull_request]
name: Dist installation

jobs:
  build:
    runs-on: 'macos-10.15'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
      - name: Test and build
        run: |
          cpanm --installdeps .
          perl Makefile.PL
          make test
          make dist
      - uses: actions/upload-artifact@v2
        with:
          name: dist-for-installation-test
          path: '*.tar.gz'
          retention-days: 1
  install-linux:
    runs-on: 'ubuntu-latest'
    needs: build
    container:
      image: perl:5.34
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist-for-installation-test
      - name: Install on Linux
        run: |
          cpanm *.tar.gz
  install-openbsd:
    runs-on: macos-10.15
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist-for-installation-test
      - name: Install on OpenBSD
        uses: cross-platform-actions/action@v0.3.1
        with:
          operating_system: openbsd
          version: 6.9
          shell: bash
          run: |
            mkdir dist-for-test &&
            tar -C dist-for-test -xzf *.tar.gz &&
            cd dist-for-test/* &&
            cpan App::cpanminus &&
            /home/runner/perl5/bin/cpanm --quiet --notest --installdeps . &&
            /home/runner/perl5/bin/cpanm -v .

