on: [push, pull_request]
name: Linux install

jobs:
  build:
    runs-on: 'macos-15'
    steps:
      - uses: actions/checkout@v5
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
      - name: Test and build
        run: |
          cpanm --installdeps .
          perl Makefile.PL
          make test
          make dist
      - uses: actions/upload-artifact@v4
        with:
          name: dist-for-linux-install
          path: '*.tar.gz'
          retention-days: 1
  install-linux:
    runs-on: 'ubuntu-latest'
    needs: build
    container:
      image: perl:5.34
    steps:
      - uses: actions/download-artifact@v5.0.0
        with:
          name: dist-for-linux-install
      - name: Install on Linux
        run: |
          cpanm *.tar.gz
