on: [push, pull_request]
name: Install on various OSes

jobs:
  build:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v6
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
      - name: Test and build
        run: |
          cpanm --installdeps .
          perl Makefile.PL
          make test
          make dist
      - uses: actions/upload-artifact@v6
        with:
          name: dist-for-install
          path: '*.tar.gz'
          retention-days: 1
  install-linux:
    runs-on: 'ubuntu-latest'
    needs: build
    container:
      image: perl:5.34
    steps:
      - uses: actions/download-artifact@v7.0.0
        with:
          name: dist-for-install
      - name: Install on Linux
        env:
          AUTOMATED_TESTING: 1
          PERL_MM_USE_DEFAULT: 1
        run: |
          mkdir dist-for-test &&
          tar -C dist-for-test -xzf *.tar.gz &&
          cd dist-for-test/* &&
          cpanm --installdeps . &&
          perl Makefile.PL &&
          perl -V|grep .vsize &&
          make test TEST_VERBOSE=1
  install-32bit-linux:
    runs-on: 'ubuntu-latest'
    needs: build
    container:
      image: i386/debian:trixie-slim
    steps:
      - name: Install on 32-bit Linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPOSITORY: ${{ github.repository }}
          AUTOMATED_TESTING: 1
          PERL_MM_USE_DEFAULT: 1
        run: |
          apt-get update && apt-get install -y unzip curl jq build-essential &&
          curl -L -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${GH_TOKEN}" -o dist-for-install.zip $(curl -L -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${GH_TOKEN}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${GH_REPOSITORY}/actions/artifacts -o -|jq -r '[.artifacts.[]|select(.expired == false)]|max_by(.created_at).archive_download_url') &&
          curl -o perl-5.42.0-src.tar.gz https://cpan.metacpan.org/authors/id/B/BO/BOOK/perl-5.42.0.tar.gz &&
          tar xzf perl-5.42.0-src.tar.gz &&
          rm perl-5.42.0-src.tar.gz &&
          cd perl-5.42.0 &&
          sh Configure -de -Dprefix=$HOME/perl-5.42.0-installed &&
          make -j $(nproc) &&
          make install &&
          cd .. &&
          unzip dist-for-install.zip &&
          mkdir dist-for-test &&
          tar -C dist-for-test -xzf *.tar.gz &&
          cd dist-for-test/* &&
          $HOME/perl-5.42.0-installed/bin/perl -MCPAN -e 'install qw(App::cpanminus)' &&
          $HOME/perl-5.42.0-installed/bin/cpanm --installdeps . &&
          $HOME/perl-5.42.0-installed/bin/perl Makefile.PL &&
          $HOME/perl-5.42.0-installed/bin/perl -V|grep .vsize &&
          make test TEST_VERBOSE=1
  install-netbsd:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - uses: actions/download-artifact@v7.0.0
        with:
          name: dist-for-install
      - name: Install on NetBSD
        env:
          AUTOMATED_TESTING: 1
          PERL_MM_USE_DEFAULT: 1
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: netbsd
          version: 10.1
          shell: bash
          run: |
            echo "PKG_PATH=https://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/amd64/10.1/All" | sudo tee -a /etc/pkg_install.conf &&
            sudo pkgin -y update &&
            sudo pkgin -y install perl &&
            mkdir dist-for-test &&
            tar -C dist-for-test -xzf *.tar.gz &&
            cd dist-for-test/* && # sudo pkg install -y perl5 &&
            perl -MCPAN -e 'install qw(App::cpanminus)' &&
            /home/runner/perl5/bin/cpanm --installdeps . &&
            /home/runner/perl5/bin/cpanm -v .
  install-freebsd:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v7.0.0
        with:
          name: dist-for-install
      - name: Install on FreeBSD
        env:
          AUTOMATED_TESTING: 1
          PERL_MM_USE_DEFAULT: 1
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: freebsd
          version: 14.2
          shell: bash
          run: |
            mkdir dist-for-test &&
            tar -C dist-for-test -xzf *.tar.gz &&
            cd dist-for-test/* &&
            sudo pkg install -y perl5 &&
            cpan App::cpanminus &&
            /home/runner/perl5/bin/cpanm --installdeps . &&
            /home/runner/perl5/bin/cpanm -v .
  install-openbsd:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v7.0.0
        with:
          name: dist-for-install
      - name: Install on OpenBSD
        env:
          AUTOMATED_TESTING: 1
          PERL_MM_USE_DEFAULT: 1
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: openbsd
          version: 7.4
          shell: bash
          run: |
            mkdir dist-for-test &&
            tar -C dist-for-test -xzf *.tar.gz &&
            cd dist-for-test/* &&
            cpan App::cpanminus &&
            /home/runner/perl5/bin/cpanm --quiet --notest --installdeps . &&
            /home/runner/perl5/bin/cpanm -v .

  install-omnios:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - uses: actions/download-artifact@v7.0.0
        with:
          name: dist-for-install
      - name: Install on OmniOS
        env:
          AUTOMATED_TESTING: 1
          PERL_MM_USE_DEFAULT: 1
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: omnios
          version: r151056
          shell: bash
          run: |
            sudo pkg install archiver/gnu-tar developer/gcc14 &&
            mkdir dist-for-test &&
            gtar -C dist-for-test -xzf *.tar.gz &&
            cd dist-for-test/* &&
            cpan App::cpanminus &&
            /home/runner/perl5/bin/cpanm --installdeps . &&
            /home/runner/perl5/bin/cpanm -v .
