on: [push, pull_request]
name: MacOS

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: ['macos-13', 'macos-11', 'macos-12']
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
      - name: Test and build
        run: |
          cpanm --installdeps .
          perl Makefile.PL
          make test
