on: [push, pull_request]
name: OpenBSD

jobs:
  build:
    runs-on: 'macos-12'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
      - name: Test and build
        run: |
          cpanm --installdeps .
          perl Makefile.PL
          make test
          make dist
      - uses: actions/upload-artifact@v4
        with:
          name: dist-for-openbsd-install
          path: '*.tar.gz'
          retention-days: 1
  install-openbsd:
    runs-on: macos-12
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-for-openbsd-install
      - name: Install on OpenBSD
        uses: cross-platform-actions/action@v0.22.0
        with:
          operating_system: openbsd
          version: 6.9
          shell: bash
          run: |
            mkdir dist-for-test &&
            tar -C dist-for-test -xzf *.tar.gz &&
            cd dist-for-test/* &&
            cpan App::cpanminus &&
            /home/runner/perl5/bin/cpanm --quiet --notest --installdeps . &&
            /home/runner/perl5/bin/cpanm -v .

